language: python
os:
  - linux

python:
  - "3.6" # issue with pymsql when using 3.8
  # PyPy versions
  - "pypy3"  # currently Python 3.6.1,  PyPy 7.1.1-beta0
# command to install dependencies
install:
  - pip install --upgrade cython
  - pip install -r requirements.txt --extra-index-url https://test.pypi.org/simple/
# command to run tests
script: pytest
