language: python
os:
  - linux

python:
  - "3.6" # issue with pymsql when using 3.8
  # PyPy versions
  - "pypy3"  # currently Python 3.6.1,  PyPy 7.1.1-beta0
# command to install dependencies
before_install:
  - sudo apt-get -y install freetds-bin
install:
  - pip install -r requirements.txt --extra-index-url https://test.pypi.org/simple/
  - pip install . # install emtask package
# command to run tests
script: pytest
