language: python
os:
  - linux

python:
  - "3.6" # issue with pymsql when using 3.8
  # PyPy versions
install:
  - pip install -r requirements.txt --extra-index-url https://test.pypi.org/simple/
  - pip install . # install emtask package
# command to run tests
script: pytest
